### ISSUE TITLE
[BUG] CodeBlock

### ISSUE THREAD

**Issue by agcrisbp** [once-ui-system/magic-portfolio#17]
### Explanation

If multiple CodeBlocks are inserted in one MDX file, it will not work.

- For example:
![Screenshot_2024-11-25-01-46-19-065_com foxdebug acode](https://github.com/user-attachments/assets/507db286-25ac-4759-bac0-f8706279bba3)

### Results

- Vercel:
![Screenshot_2024-11-25-01-35-04-029_com vivaldi browser](https://github.com/user-attachments/assets/9ebc14a0-7593-49f9-b660-44e5d78da6f3)

- Local Terminal:
![Screenshot_2024-11-25-01-37-41-698_com termux](https://github.com/user-attachments/assets/791c3b61-64b1-41bf-a1fe-1a7538a372da)

### Edit
- I already remove the backticks inside the 2nd CodeBlock, and remains the same.

**Comment by lorant-one** [comment]
hey thanks for reporting @agcrisbp, does it work locally?

**Comment by agcrisbp** [comment]
> hey thanks for reporting @agcrisbp, does it work locally?

nope, the 2nd result screenshot was the only thing the error report says.

**Comment by lorant-one** [comment]
i don't know what could be the issue, since the code you provided works perfectly fine for me. did you make any progress with this since?

![image](https://github.com/user-attachments/assets/29ed7f8f-0768-4698-bba6-c69d8b53b7ff)
