### ISSUE TITLE
Copied blog link does not jump to heading section

### ISSUE THREAD

**Issue by spiritanand** [once-ui-system/magic-portfolio#20]
I tried copying the subheading of my blog and it does not jump to that section of the page.

Why is this an issue? Am I missing something?

https://stackoverflow.com/a/72345455

**Comment by lorant-one** [comment]
oh thanks for reporting this @spiritanand i tested it and it in fact doesn't jump to the heading element. i'm going to take a closer look and fix it!

**Comment by lorant-one** [comment]
you absolutely can @spiritanand, i won't have time to deal with this during the weekend, so if you find a solution, feel free to open a pr! every contributor gets a honorable mention on [once-ui.com](https://once-ui.com/sponsors) :)

**Comment by dineshkidd** [comment]
@lorant-one Have raised a pr for this one. #24

**Comment by lorant-one** [comment]
thanks a lot for your contribution @dineshkidd i'm going to review it tomorrow! :)

**Comment by lorant-one** [comment]
closing this since it's been fixed, but we're still looking for a simpler solution.
