### ISSUE TITLE
Sticky Profile Avatar

### ISSUE THREAD

**Issue by tech-savvy-guy** [once-ui-system/magic-portfolio#23]
I was wondering if it would be possible to make the profile avatar in the `About Me` page sticky in desktop devices? That would allow my profile to be always visible and would also get rid of the negative space to the left. I have attached a screenshot to further explain this.

I tried editing it on my own, but the project structure is a bit too complicated for me to understand.

It would be great if this could be fixed. Thanks.

![image](https://github.com/user-attachments/assets/00678456-d273-4e20-a092-7ce16fb3f1eb)

**Comment by lorant-one** [comment]
thanks for the suggestion @tech-savvy-guy, i really like this idea! let me know if there's an easy way to do this.

**Comment by tech-savvy-guy** [comment]
Hey, thanks for the reply! I managed to get rid of the negative space by adding a "Now Playing" custom Spotify component. 

![image](https://github.com/user-attachments/assets/d76b43e1-092b-4c14-b4db-8396bd2b1cf8)

However, the layout is a bit too complicated for me to make any changes without breaking everything. I will need some guidance.

P.S. I had to edit the `Feedback` Component just to make this Spotify thing work 😓

**Comment by tech-savvy-guy** [comment]
I also had a doubt, how did you manage to make this `InlineCode` work on your website?

![image](https://github.com/user-attachments/assets/10daf816-976b-4990-ac86-3405cd354ef3)

I am guessing it's the `SmartLink` component, but when I use the same I get the output on a different line.

![image](https://github.com/user-attachments/assets/c319d76e-128a-48f2-92a1-705e330e6205)

The above one uses the `SmartLink` component.

![image](https://github.com/user-attachments/assets/52edb9a0-f2dc-4925-a8fd-2f8a5862b106)

The above one uses the `InlineCode` component.

This is what I am editing in the `content.js` file:

```js
    intro: {
        display: true,
        title: 'Introduction',
        description: <>I’m a <InlineCode>tech-savvy-guy</InlineCode> passionate about turning ideas into impactful solutions. I thrive on making complex problems simple and creating software that makes a difference. I’m so good at multitasking, I can code, procrastinate, and find bugs all at once!</>
    },
```


Can you help me with this too?

**Comment by lorant-one** [comment]
sure thing! here's how i updated the about.description.intro for my own:

```<>I’m a Vienna-based design engineer with a passion for all things creative. I <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}><Link href="/work">design and build</Link></InlineCode> web apps, <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}><Link href="https://github.com/lorant-one" target="_blank">contribute</Link></InlineCode> to open-source projects, experiment with generative AI, <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}><Link href="https://creatillo.com" target="_blank">paint digitally</Link></InlineCode> and occasionally pick up a pen to <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}><Link href="/blog/from-my-sketchbook">sketch</Link></InlineCode> on paper.</>```

my own portfolio is running on an old version when there wasn't a SmartLink so I had to do compensate with inline styles :) i'll try to update it with the SmartLink and see if I can get it to work without breaking the layouts since that would be simpler.

**Comment by tech-savvy-guy** [comment]
Thanks for the reply, but when I copy paste the same, it does not work (I removed the `Link` component as I don't require it)

```
    intro: {
        display: true,
        title: 'Introduction',
        // description: <>I’m a tech-savvy-guy passionate about turning ideas into impactful solutions. I thrive on making complex problems simple and creating software that makes a difference. I’m so good at multitasking, I can code, procrastinate, and find bugs all at once!</>
        description: <>I’m a Vienna-based design engineer with a passion for all things creative. I <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}>design and build</InlineCode> web apps, <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}>contribute</InlineCode> to open-source projects, experiment with generative AI, <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}>paint digitally</InlineCode> and occasionally pick up a pen to <InlineCode style={{padding: 'var(--static-space-2) var(--static-space-8)'}}>sketch</InlineCode> on paper.</>
```

![image](https://github.com/user-attachments/assets/647c3998-d691-472c-8eb4-bdee90ed4dcd)

**Comment by tech-savvy-guy** [comment]
Okay, never mind I fixed it by wrapping it in a `Text` component:

```js
    intro: {
        display: true,
        title: 'Introduction',
        description: <Text style={{lineHeight: '1.6'}} >I’m a <InlineCode style={{width : 'fit-content', padding: 'var(--static-space-4) var(--static-space-8)', color: 'var(--brand-on-background-medium)'}}>tech-savvy-guy</InlineCode> passionate about turning ideas into impactful solutions. I thrive on making complex problems simple and creating software that makes a difference. I’m so good at multitasking, I can code, procrastinate, and find bugs all at once!</Text>
    },
```

**Comment by tech-savvy-guy** [comment]
> thanks for the suggestion @tech-savvy-guy, i really like this idea! let me know if there's an easy way to do this.

Could you still kindly look into this?

**Comment by lorant-one** [comment]
@tech-savvy-guy just pushed an update that includes this enhancement on the profile page. i had to add a new class in the `about.module.scss` and tweak the `about/page.tsx` a bit.

**Comment by tech-savvy-guy** [comment]
Thanks a lot! 😄
