### ISSUE TITLE
Type Error: MDXRemote cannot be used as a JSX component in CustomMDX

### ISSUE THREAD

**Issue by nxtgencat** [once-ui-system/magic-portfolio#25]
⨯ ESLint must be installed in order to run during builds: npm install --save-dev eslint
Failed to compile.
./src/components/mdx.tsx:145:10
Type error: 'MDXRemote' cannot be used as a JSX component.
  Its type '(props: MDXRemoteProps) => Promise<ReactElement<any, string | JSXElementConstructor<any>>>' is not a valid JSX element type.
    Type '(props: MDXRemoteProps) => Promise<ReactElement<any, string | JSXElementConstructor<any>>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'Promise<ReactElement<any, string | JSXElementConstructor<any>>>' is not assignable to type 'ReactNode'.
  143 | export function CustomMDX(props: CustomMDXProps) {
  144 |     return (
> 145 |         <MDXRemote
      |          ^
  146 |             {...props}
  147 |             components={{ ...components, ...(props.components || {}) }}
  148 |         />
Error: Command "npm run build" exited with 1

**Comment by lorant-one** [comment]
hey @nxtgencat can you provide a little more context? what did you change before this error appeared?

**Comment by DeniKucevic** [comment]
It shows up for me when running `npm run build`, changed nothing

**Comment by nxtgencat** [comment]
> hey @nxtgencat can you provide a little more context? what did you change before this error appeared?

I haven't changed anything, just deployed to vercel by clicking on the button below the repo

**Comment by nxtgencat** [comment]
> It shows up for me when running `npm run build`, changed nothing.
> 
> I fixed it by adding ` {/* @ts-expect-error Server Component */}` above MDXRemote in CustomMDX component.


That doesn't help either in deploying

    at e (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137542)
    at ek (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138016)
    at eP (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:141995)
    at eE (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142569)
    at Timeout._onTimeout (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135346)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
 ✓ Generating static pages (16/16)
> Export encountered errors on following paths:
	/[locale]/work/[slug]/page: /en/work/simple-project
Error: Command "npm run build" exited with 1

**Comment by nxtgencat** [comment]
> It shows up for me when running `npm run build`, changed nothing.
> 
> I fixed it by adding ` {/* @ts-expect-error Server Component */}` above MDXRemote in CustomMDX component.

Thanks, it worked!

**Comment by Licnex** [comment]
> It shows up for me when running `npm run build`, changed nothing.
> 
> I fixed it by adding ` {/* @ts-expect-error Server Component */}` above MDXRemote in CustomMDX component.

wait minute thats just a comment, how tf do you actually fix it?

**Comment by nxtgencat** [comment]
> > It shows up for me when running `npm run build`, changed nothing.
> > I fixed it by adding ` {/* @ts-expect-error Server Component */}` above MDXRemote in CustomMDX component.
> 
> wait minute thats just a comment, how tf do you actually fix it?

{/* @ts-expect-error Server Component */} tells TypeScript to ignore the error with MDXRemote in a server-side context. It doesn't fix the root issue but bypasses the TypeScript check.

**Comment by lorant-one** [comment]
thanks for the responses and the quick temporary fix @DeniKucevic, i'm still investigating this issue. i was able to create a build locally without getting this error, and i have also pushes a new update, which was deployed automatically without issues. although when i forked the repo and tried to deploy, i received the same error. it's definitely weird, but i'm trying to find the root of this :)

**Comment by lorant-one** [comment]
fyi i have suppressed ts checks for the component as a temporary solution until we figure it out. one of the related packages is being added to the package-lock with a newer version (even though we are using the same `packages.json`), and it seems to be triggering a type issue in the current mdx setup.
