### ISSUE TITLE
Question on footer

### ISSUE THREAD

**Issue by Licnex** [once-ui-system/magic-portfolio#31]
Hey, I am wanting to add stuff to the footer, but the problem is it looks really bulky and ugly with both the section mentioning the stuff I am wanting to add and the once ui promo. I have mentioned magic portfolio in the work section. So... If have your guys' blessing, could I please remove the promo in the footer?

**Comment by zsofiakm** [comment]
Hi @Licnex,

If you have a visible link back to Once UI, that works! Thanks very much for reaching out to double check.

Would love to see what you've built with the template. You could share it here or in this thread: https://github.com/once-ui-system/magic-portfolio/issues/9
