### ISSUE TITLE
Issue in Bottom Navbar in Mobile View

### ISSUE THREAD

**Issue by chmuhammadasim** [once-ui-system/magic-portfolio#6]
![image](https://github.com/user-attachments/assets/31170686-e168-4e25-b4d0-ceca15f848af)

The bottom navbar in the mobile view is misaligned because it's not properly centered. This misalignment occurs due to the width: 100% CSS property on the navbar, which stretches it across the screen and disrupts the centering of its elements.

Solution: To fix this, remove the width: 100% property. This will allow the navbar items to be centered properly, ensuring a balanced and aligned appearance in mobile view. Instead, consider using display: flex and justify-content: center to center the content effectively.

**Comment by lorant-one** [comment]
thanks for reporting this issue @chmuhammadasim — we’re going to fix it shortly!

**Comment by zsofiakm** [comment]
Hey @chmuhammadasim,
Thanks for reporting this, I fixed it here: https://github.com/once-ui-system/magic-portfolio/commit/1b43881318cec7e0f4fb62b1d7e4e520e46458fc
